### ISSUE TITLE
brokers

### ISSUE THREAD

**Issue by behrad** [strongloop/strong-mq#20]
it seems strong-mq works on activeMQ by default... Do I have another options (mqtt) for a durable topic/subscription?

**Comment by sam-github** [comment]
strong-mq doesn't work on anything by default, you have to choose the provider. But it does support stomp/active mq, amqp/rabbit mq, and node cluster mq out of the box.

You could implement a provider for MQTT, or use MQTT directly (if you don't want to write code that is agnostic as to the backend).

Btw, what do you mean by durable? If you mean persistent on disk, active and rabbit support that.
