### ISSUE TITLE
ECONNRESET error at connection !

### ISSUE THREAD

**Issue by afaucogney** [strongloop/strong-mq#23]
When using the snippet in the readme.md with RappidMQ cloud service, this is throwing back this issue ?

Error: read ECONNRESET
    at errnoException (net.js:904:11)
    at TCP.onread (net.js:558:19)

I have tried with jackrabbit, the connection is working with the server.

**Comment by sam-github** [comment]
I suspect that the cloud service is AMQP 1.0, and that https://www.npmjs.com/package/amqp is AMQP 0.9, and thus the server is resetting the connection.

Please report to amqp, or to rabbit.
