### ISSUE TITLE
Subscribe to multiple topics not supported by native adapter

### ISSUE THREAD

**Issue by bajtos** [strongloop/strong-mq#5]
As a sl-mq user, I want to use a single sub-queue to receive updates on multiple topics.

``` javascript
sub.subscribe('connect', onConnectFn);
sub.subscribe('close', onCloseFn);
// etc.
```

The current API gives an impression that it should be possible. The implementation in the native adapter does not seem to support this use-case.

I also want to selectively unsubscribe from some topics, e.g.

``` javascript
sub.unsubscribe('connect');
// still subscribed to 'close' topic
```

Is this a missing feature, or am I trying to use the API incorrectly (given it's not possible to subscribe to multiple topics in the first place)?

**Comment by gkTim** [comment]
I ran into the same problem.
Can you provide an example on how to subscribe to different topics on the same queue?

I would expect that the callback is only called for the appropriated topic.

Here is my code and `cache.set` gets called but I published a `cache.get` message.

``` javascript
var subQueue = connection.createSubQueue('mq-cache');
  var pubQueue = connection.createPubQueue('mq-cache');

  subQueue
  .subscribe('cache.get', (msg) => {
    Cacheitem.readCacheitem(msg.type, msg.key, (err, data) => {
      if (err) return;

      pubQueue.publish(data, 'cache.get.result.' + msg.key);
    });
  })
  .subscribe('cache.set', (msg) => {
    Cacheitem.writeCacheitem(msg.type, msg.key, msg.data, (err, data) => {

    });
  });
```

**Comment by sam-github** [comment]
@gkTim Why are you using strong-mq? It does what it does... but we never found it useful and are no longer developing it.

Every person who I've heard from who is trying to use it misunderstands what its for, and would be better off using something else, which is why I ask what your purpose is.

**Comment by gkTim** [comment]
@sam-github Thanks for your answer.

In my case I would like to use it to create rabbit-mq message queues so my different microservices can communicate without knowing each other directly. Also I want to use work queues to load balancing the work between multiple instance of a service.

Am I getting the wrong idea of strong-mq and there is a better way to do this with strongloop and rabittMQ?
At the moment It does what I expected expect the above mentioned.

**Comment by sam-github** [comment]
It would be better to directly use the underlying module, I added a note to this effect:

https://github.com/strongloop/strong-mq#strong-mq-clustering-of-applications-on-top-of-message-queues
